# Generated by Django 5.1.4 on 2026-07-14 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=50)),
                ('plataforma', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='juegos/')),
                ('descripcion', models.TextField(blank=True)),
                ('anio', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('jugando', 'Jugando'), ('completado', 'Completado'), ('pendiente', 'Pendiente'), ('abandonado', 'Abandonado')], default='pendiente', max_length=20)),
                ('puntaje', models.IntegerField(blank=True, null=True)),
                ('resenia', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_juego', to='juegos.juego')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juegos_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'juego')},
            },
        ),
    ]
