# Generated by Django 5.1.4 on 2026-06-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='estado',
            field=models.CharField(choices=[('jugando', 'Jugando'), ('completado', 'Completado'), ('pendiente', 'Pendiente'), ('abandonado', 'Abandonado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='juego',
            name='puntaje',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='juego',
            name='resenia',
            field=models.TextField(blank=True),
        ),
    ]
