# Generated by Django 5.1.4 on 2026-06-18 18:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0002_juego_estado_juego_puntaje_juego_resenia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='juegos_favoritos', to=settings.AUTH_USER_MODEL),
        ),
    ]
